FROM gcc:7.4

COPY Makefile .
COPY build/get_ram_usage .
COPY restbed .

WORKDIR .
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:.

RUN apt-get update
RUN apt-get install -y libssl1.1
RUN apt-get install -y libcurl4
RUN apt-get install -y make

EXPOSE 10000

CMD ["make run_ram"]
