{
 "title": "SET Challenge",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM Occupation",
   "type": "graph",
   "description": "Occupazione percentuale di RAM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "ram" }
   ]
  },
  {
   "title": "Latency from Gateway",
   "type": "graph",
   "description": "Latenza di rete dal gateway",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    { "expr": "latency" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "description": "Carico della CPU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "cpu" }
   ]
  },
  {
   "title": "IP Gateway",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "gateway" }
   ]
  }
 ]
}